-- Places she has used before, so an address is typed once rather than every
-- time. Generated by `prisma migrate dev --create-only` against the local
-- Postgres and applied with `migrate deploy` — unlike the workshops migration,
-- which had to be hand-written because no database was reachable that day.
--
-- Nothing existing is dropped or rewritten: one nullable column is added to
-- Workshop, and the four address columns there stay exactly as they were. They
-- remain what the public page renders; the table below only fills them in.

-- AlterTable
ALTER TABLE "Workshop" ADD COLUMN     "venueId" INTEGER;

-- CreateTable
CREATE TABLE "Venue" (
    "id" SERIAL NOT NULL,
    "name" TEXT NOT NULL,
    -- Prose, one line per line — the same shape the workshop keeps, because
    -- one is copied into the other.
    "addressLines" TEXT NOT NULL,
    "postcode" TEXT NOT NULL,
    "gettingThere" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Venue_pkey" PRIMARY KEY ("id")
);

-- AddForeignKey
-- ON DELETE SET NULL, deliberately NOT cascade: deleting a place must leave
-- every workshop that used it standing, with the address it went out with.
ALTER TABLE "Workshop" ADD CONSTRAINT "Workshop_venueId_fkey" FOREIGN KEY ("venueId") REFERENCES "Venue"("id") ON DELETE SET NULL ON UPDATE CASCADE;
